- styles/blocks/callout.css
Now supports 3 columns if you include `.three` in the block name. Also resolved some link styles.
> fix: call out cards now supports three columns

- templates/stock-advocates/stock-advocates.css
- templates/stock-advocates/stock-advocates.js
I didn't want to do this by adding an <a> tag at runtime, because there is lots of code that uses like header.children[0] and expects the img tag there.
Instead, I added an onclick event and a style to show a cursor. For the middle "Adobe Stock Advocates" logo, I had it link to the index of the current directory (using a calculation on window.location.pathname)
I'm not sure what to link the home page to, because there is /stock/en/ but there is nothing there in adobe pages, ie this:
https://pages--adobe.hlx.page/stock/en/
returns a 404, if I remove the language
https://pages--adobe.hlx.page/stock/
also gives an error. I don't know how this will be deployed exactly so I could hardcode a URL but I wouldn't know what it is.
For now I used a variant of the code that takes us to /stock/en/ (or …
> adds click handler and pointer style to header images

- templates/tl/tl.js
Location of download file was not pointing in the right location inside the href=""
Current -> pages.adobe.com/photoshop/en/twp3/design/file-name.zip
new -> pages.adobe.com/static/twp3/practice-files/file-name.zip
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.
> File location fix for twp template

- templates/default/checklist.js
- templates/tl-masterclass/tl-masterclass.css
Fixed step page headline color on Premiere Pro tl-masterclass single page
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
> Headline color fix for tl-masterclass single page

- templates/learn/learn.css
- templates/tutorials/tutorials.css
- templates/tutorials/tutorials.js
CSS and JS updates to Tutorial template for HSL and LrC + Ps page. Added a wee bit of markup + styling for new card section at the bottom. Fixed line height on paragraphs/cards to be 27px instead of 25px.
CSS updates to Tutorial template for CCP version of Color Grading tutorial, adding revised card section styling and fixing mobile bugs.
> Updates to Learn and Tutorial template for LrC pages

- templates/tl/tl.js
Applies to only pages that rely on the TL template and are within the photography-plan directory.
> remove timeline feature for photography-plan pages

- tools/sidekick/config.js
Since the switch to #322 the parent folder plugin bombs...
> fix(sidekick): js error in parent folder plugin

- tools/sidekick/config.js
- Fix `sk is already defined` error
- Reload browser cache after `PURGE`
> fix(sidekick): js error in gdoc and browser cache handling

- pages/scripts/scripts.js
pages using template and header.html: 
https://header-fix--pages--adobe.hlx3.page/photoshop/br/tl/design/step?1
https://header-fix--pages--adobe.hlx3.page/illustrator/en/tl/thr-layout-home/
pages using nav block: 
https://header-fix--pages--adobe.hlx3.page/cc-growth-sandbox/test/blocks
https://header-fix--pages--adobe.hlx3.page/photoshop/en/prerelease-api/
pages with blocks, no template, and header.html (fixed):
https://header-fix--pages--adobe.hlx3.page/character/en/body-tracker
> fix: load header.plain.html on non-templated pages if no nav block

- templates/stock-advocates/stock-advocates.css
Fix additional bugs on hero banners due to vh value not having a min-height, for example:
https://advocates-pages--pages--webistry-development.hlx3.page/stock/en/advocates/
before:
after:
https://advocates-pages--pages--webistry-development.hlx3.page/stock/en/advocates/artist-development-fund
before:
after: 
Also fixed the positioning of artist in artist feature page: 
https://advocates-pages--pages--webistry-development.hlx3.page/stock/en/advocates/artists/adam-perez
before:
after:
> fix(advocates-pages): fix additional bugs on hero banners

- templates/stock-advocates/stock-advocates.css
- templates/stock-advocates/stock-advocates.js
- Fixed the mobile menu not closing properly when clicking an anchor link, preventing scroll
- Fixed some artists pictures being hidden on mobile, for example:
https://pages.adobe.com/stock/en/advocates/artists/amaal-said
before:
after:
https://pages.adobe.com/stock/en/advocates/artists/sophie-alp
before: 
after:
Some pictures were working but not others... this will pull request fix it
> fix(advocates-artists): Bug fixes: mobile menu not closing properly on anchor click & fix artist pages some pictures being hidden

- pages/scripts/scripts.js
Added an updated year to the footer and removed the hard coded year value with `new Date()` method.
example, footer on this page.
- https://footer--pages--adobe.hlx3.page/illustrator/en/tl/thr-layout-home/
> Added current year to footer copyright.

- templates/consonant/consonant.js
Fixed links to open to new tab if the url is external.
Automatically fixes the following links behaviors (as requested):
URL for testing:
- https://fix-links-new-tab--pages--Webistry-Development.hlx3.page/stock/en/artisthub/drafts/artisthub-2.2/
The menu items in this example should be the following: 
Home -> `/stock/en/artisthub/drafts/artisthub-2.2/`
Requested Behavior: Does not open in new tab
Get Started -> `/stock/en/artisthub/drafts/artisthub-2.2/get-started`
Requested Behavior: Does not open in new tab
Learn -> `/stock/en/artisthub/drafts/artisthub-2.2/learn`
Requested Behavior: Does not open in new tab
Learn/Research Insights -> `/stock/en/artisthub/drafts/artisthub-2.2/learn/research-insights`
Requested Behavior: Does not open in new tab
Get Inspired -> …
> fix(consonant-blocks): fix links opening in new tab as requested

- pages/blocks/textoverbackground/textoverbackground.css
Any element that gets a `<strong>` element like:
`<h1><strong>Titlte</strong></h1>`
will get a heavier font size. 
exmaple:
https://text-over-background--pages--adobe.hlx3.page/express/en/learn/thank-you
> added heavier font weight for h1s that container strong text

- templates/consonant/blocks/share/share.js
- templates/consonant/consonant.js
https://artisthub_sharing_block--pages--webistry-development.hlx3.page/stock/en/artisthub/drafts/artisthub-example/learn/research-insights/industry-insights-financial-services
This is inspired from David's sharing facilities on the blog refactor, example URL can be found here:
https://blog-refactor--express-website--adobe.hlx3.page/drafts/pdooley/blog/introducing-creative-cloud-express
It seems that Facebook's link won't work locally, but when tested with the proper live urls it works as expected, therefore I would consider launching it and monitoring the situation when the pages go live.
Additionally, I've imported the createTag function into consonant.js. If you would rather that i use directly from script.js let me know!
> Artist Hub sharing block

- helix-query.yaml
Set up the helix-query.yaml and the query-index spreadsheet in Drive.
JSON is coming back on a test URL - https://admin.hlx.page/index/adobe/pages/query-index/premiere/en/yts-livestream
Items won't index until the queue is setup in AWS.
> Query Index Setup

- templates/consonant/blocks/cards/cards.css
- templates/consonant/blocks/cards/cards.js
- templates/consonant/blocks/marquee/marquee.css
- templates/consonant/blocks/marquee/marquee.js
- Added video to the cards block
- Fix bug where marquee with empty content would hide the background image/video in mobile-tablet view
- Vertically centered the marquee background image/video in desktop view
- Fixed card's play icon position on smaller screen
[before](https://main--pages--adobe.hlx.page/stock/en/artisthub/drafts/block-test) / [after](https://style-fixes--pages--webistry-development.hlx.page/stock/en/artisthub/drafts/block-test)
> fix(consonant): video in cards block + style fixes for empty-text marquee block.

- templates/consonant/blocks/marquee/marquee.css
- Fix empty line on the right of video in desktop view
- Fix missing selector in one of the css styles which prevents some marquees to show up in desktop view
[before](https://main--pages--adobe.hlx.page/stock/en/artisthub/get-inspired/creative-trends/visual-trend-in-the-groove-call-for-stock-content) / [after](https://small-fix--pages--webistry-development.hlx.page/stock/en/artisthub/get-inspired/creative-trends/visual-trend-in-the-groove-call-for-stock-content)
> fix(consonant): fix line on the right of video, fix missing selector

- templates/consonant/blocks/columns/columns.css
- templates/consonant/blocks/columns/columns.js
- templates/consonant/blocks/marquee/marquee.css
- templates/consonant/consonant.js
Feature request on Airtable:
"With a large featured image many users will try clicking on the image itself expecting it to link. Can we add behavior so that for featured pods, the image links to the same page as the CTA button?
IF there are multiple CTAs it should link to the primary CTA. If there is no primary CTA but there are two buttons, then it should link tot he first one.
IF there is no button then no link on image."
- If the image is surrounded by a link, use that link.
- If the image is not surrounded by a link, look for the primary CTA or first CTA in the same row and use that as a link.
- If there is no CTA, the image has no link.
Test URL:
https://columns--pages--webistry-development.hlx.page/stock/en/artisthub/drafts/block-test …
> feature request (columns): if image has no link, add link to first CTA button

- templates/default/default.js
- templates/learn/learn.js
- templates/mobile-awareness/mobile-awareness.js
Resolving Issue ticket:
[MWPW-111004](https://jira.corp.adobe.com/browse/MWPW-111004)
- Added redirect via JS since this is more like logical bug from learn module.
- Also removed default.css importing code from two places since it doesn't exist it will help 404 issue. 
(This is not related to ticket) - example page: https://pages.adobe.com/documentation/en/authoring-pages
Testing Pages:
https://main--pages--adobe.hlx.live/creativecloud/es/photography-plan/lightroom-classic/crop-emphasis/step
https://step-redirect--pages--adobe.hlx.live/creativecloud/es/photography-plan/lightroom-classic/crop-emphasis/step
https://main--pages--adobe.hlx.live/creativecloud/es/photography-plan/lightroom-classic/sunrise-pop/step
https://step-redirect--pages--adobe.hlx.live/creativecloud/es/photography-plan/li …
> Redirect to step 1, if no step index specified.

- templates/default/default.js
- templates/mobile-awareness/mobile-awareness.js
[Jasper](https://adobedotcom.slack.com/team/WC7QCQPV2), asks where the default.css went:
"Hi all! I developed the template for the Growth squad's [Apps In Your Plan](https://pages.adobe.com/creativecloud/en/mobile-apps-in-your-plan/cpp) discovery page a few months back, and all was well. Now, however, the page is missing the base Adobe stylesheet.
My code was pointing to https://pages.adobe.com/pages/styles/default.css , but that file has clearly been moved or deleted since. (see https://github.com/adobe/pages/tree/main/pages/styles)
Can anyone point me to where that file went?"
I see the footer is broken due to missing default.css.
Current:
https://main--pages--adobe.hlx.page/creativecloud/en/mobile-apps-in-your-plan/cpp
Test:
https://default-css--pages--adobe.hlx.page/creativecloud/en/mo …
> bring the default.css back with corrected path.

- templates/stock-advocates/stock-advocates.css
Fix 2 visual bugs:
- In all the pages the St logo on the top left side of the page is distorted on the ST black square
- In Veterans return page - the image grid is broken.
Test url:
- Homepage ( [Before](https://main--pages--adobe.hlx.page/stock/en/advocates/) / [After](https://main--pages--webistry-development.hlx.page/stock/en/advocates/) )
- Veterans page ( [Before](https://main--pages--adobe.hlx.page/stock/en/advocates/veterans-return) / [After](https://main--pages--webistry-development.hlx.page/stock/en/advocates/veterans-return) )
> fix(advocates): fix 2 visual bugs

- templates/tl/styles.css
Broken icon on: https://pages.adobe.com/illustrator/en/tl/thr-illustration-home/
After:
- https://v7-tl--pages--adobe.hlx.page/illustrator/en/tl/thr-illustration-home/
This page is correct but is also using the tl template (here only to verify potential regressions)
Before:
- https://main--pages--adobe.hlx.page/photoshop/en/14-day-trial/design/
After:
- https://v7-tl--pages--adobe.hlx.page/photoshop/en/14-day-trial/design/
> fix: tl template fix
