adobe/pages

scripts.js
scripts/in-app.js
scripts/twp3.js
styles/default.css
styles/illustrator/default.css
styles/xd/in-app.css

Render header directly from gdoc and style updates.

header component update

---

styles/ihearttech/default.css

Adding styles for Cards and Fonts

Styles for ihearttech cards

---

styles/ihearttech/default.css

Adding some corretion for ihearttech cards home 
@ispykenny  could you help me with this PR

cards styles

---

components/en/beta-form.embed.html
icons/checkbox.svg
styles/premiere/speechtotext.css

Pretty straightforward – this is HTML and CSS for the S2T form, no global changes since the form stuff is an embed and the new CSS is in its own file. Please merge ASAP. Thank you!

Speech to text form embed HTML + CSS

---

styles/ihearttech/default.css

Hi @ispykenny could you help me with this one

color banner

---

styles/premiere/speechtotext.css

Only one file edited here with no global changes for speech to text pages.

More speech to text CSS

---

components/en/beta-form.embed.html
components/en/wg-form.embed.html
scripts.js
scripts/default.js
styles.css
styles/creativecloud/default.css
styles/premiere/speechtotext.css

"If __ is checked then show ___ question" type JS plus some other CSS tweaks for speech to text.

Additional JS and CSS for speech to text form

---

components/en/beta-form.embed.html

Removing bad line in speech to text form JS

---

components/en/beta-form.embed.html
scripts.js
scripts/default.js
scripts/ete.js
scripts/in-app.js
scripts/max.js
scripts/step-by-step.js
scripts/twp.js
scripts/twp3.js
scripts/twpds.js
styles.css

- changed input type of emails fields to `email`
- added custom validation error to email fields (`field.setCustomValidity()`)
- enabled/disabled required flag for radios of `work-purpose` and `profession`
- added custom validation for checkboxes (at least 1 selected)
- ensured that checkboxes were recorded properly in values array
- fixed minor typos
also see:
- https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Complex_constraints_using_the_Constraint_Validation_API

working on beta form

---

components/en/name-email-form.embed.html
styles/indesign/default.css

Another form, borrowed CSS and JS from WG and S2T

Adding an embed for the InDesign early access form + CSS for it

---

components/en/beta-form.embed.html
components/en/name-email-form.embed.html
styles/indesign/default.css

Changed placeholders + header styling on Id form
Altered submit button on Pr form

Small CSS and HTML changes on the 2 MAX forms (Pr and Id)

---

components/en/back-next-steps.embed.html

Last step of tutorial was not providing custom nav to launch app and return to tutorial start. Now that's fixed

Fixing a lil buggy that was messing up the last step of the tutorial

---

components/en/wg-form-default-v2.embed.html

Code clean up for labels and input settings.
Checkbox support

Form clean up

---

components/en/wg-form-default-v2.embed.html
icons/on24.js
styles/creativecloud/on24.css

added on24 env

---

components/en/wg-form-default-v2.embed.html

resolving array dot notation

---

styles/ihearttech/default.css

Adding CTA type button to video cards
@ispykenny could you help me with this PR

cards video cta

---

components/en/wg-form-default-v2.embed.html

clean up with the form data that gets sent off to the sheet.

form data post update

---

styles/premiere/speechtotext.css

No other pages will be impacted, just S2T.

Some CSS updates for Premiere speech to text.

---

scripts/step-by-step.js
styles/lightroom-classic/learn.css

All these changes only impact LrC tutorials.

Lightroom Classic tutorial styling and fixes for layout of index pages

---

scripts/step-by-step.js
styles/lightroom-classic/learn.css

Making cards for root color grading page point to link in Gdoc table via JS, plus some small CSS touches

More CSS and JS changes for Lr Classic tutorials

---

components/en/forms.js
components/en/wg-form-default-v2.embed.html
styles/creativecloud/default.css

Added a loader component while form generates

Kenny dynamic form generator

---

components/en/wg-form-slck.embed.html

Text update in twp wg form

---

components/en/wg-form-slckcc.embed.html
components/en/wg-form-slckfeedback.embed.html

Fixed some spelling errors in form.

Additional slack forms updated

---

components/en/back-next-steps.embed.html
components/en/tutorial-context.embed.html
scripts/step-by-step.js
styles/lightroom-classic/learn.css

Added step _ of _ to top of tutorial page, re-did content of all steps page, added handling for tutorial metadata in first step, misc styling stuff. Everything only impacts LrC tutorials

Lightroom Classic tutorial finessing

---

components/en/wg-form-default-v2.embed.html

Still WIP but submits to sheets correctly. Will rework into table layout

Updated form include

---

components/en/photoshop-nps.md
styles.css

All markup changed is NPS form only. No inputs were changed, just post-form message markup + adding a label to the form.
CSS mostly impacts NPS form but I did also add some global form styling to standardize submit button styles and add Adobe Clean to all form inputs.

Form styling for NPS form and other forms

---

components/en/form.embed.html
components/en/slide-form.js
styles/creativecloud/smb.css
styles/creativecloud/thank-you.css

Progress indicator tracking current-slide-index/slide.length

SMB style and progress indicator improvements

---

templates/stock-advocates/stock-advocates.css

Style changes for stock advocates section.
From document Advocates landing page – Helix CSS fixes, notes on completion are in that document.

Advocates landing page – Helix CSS fixes 2

---

templates/tl-masterclass/tl-masterclass.css

text color change to header on tl-masterclass template
The current text color is not legible. This change resolved this issue.
Tested across other live pages
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [ x] All new and existing tests passed.

fixed header color on tl-masterclass

---

templates/stock-advocates/stock-advocates.css

Simple style changes for two includes on bottom of advocates index
Additional commit adds style for new layout on artist-development-fund
see https://pages--digital-pi.hlx.page/stock/en/advocates/

Advocates index page footer styling

---

templates/stock-advocates/stock-advocates.css
templates/stock-advocates/stock-advocates.js

add .left-justify to all columns not on the index page
the submitandgetfunded embed submit stays centered

Additional stock advocates changes for all briefs

---

templates/stock-advocates/stock-advocates.js

fixes negative number bug in carousel code
hardcodes link for stock home

Latest changes for Stock Advocates

---

styles/blocks/checklist.css
styles/blocks/clvideo.css
styles/blocks/iframe.css
styles/blocks/instructions.css
styles/blocks/missionbg.css
styles/blocks/missiontimeline.css
styles/blocks/transcript.css
templates/default/checklist.js
templates/default/default.css
templates/default/default.js
templates/default/iframe.js
templates/default/mission-series/background.js
templates/default/mission-series/iframe.js
templates/tutorials/tutorials.css
templates/tutorials/tutorials.js

Yeah the template system is a legacy system but like. I need a new template. So this is me beginning to make one
Tutorial pages that need left-aligned text and other styles that aren't landing page friendly will use this template.
Just setting up the directory and placeholder files in this commit.

New template for simple tutorial pages

---

styles/blocks/checklist.css
templates/default/checklist.js
templates/tl-masterclass/tl-masterclass.css

Changed the white headline text from #ffffff to #000000 as this text lives in a white background. 
Tested across local, dev and other pages that share this template
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.

Headline color text correction tl-masterclass

---

templates/tl/tl.js

Download practice file CTA pointing to wrong file location for internally hosted files.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code style of this project.

edge case fix for http urls

---

components/en/three-cards.embed.html
styles/blocks/checklist.css
styles/blocks/clvideo.css
styles/blocks/next.css
templates/default/checklist.js
templates/default/default.js

Non-breaking style changes. Applied to Photoshop and Lightroom Growth test pages.

Checklist video template

---

templates/default/default.js

Allowing  our `.callout` card components to have the same button placement if `.eq` is included in the component. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project.

Equalizer functionality implementation

---

styles/blocks/iframe.css
styles/blocks/instructions.css
styles/blocks/missionbg.css
styles/blocks/missiontimeline.css
templates/default/default.css

Small CSS updates to mission template 
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ x] My code follows the code style of this project.

Mission template revisions

---

templates/default/mission-series/background.js
templates/default/mission-series/iframe.js

js code clean up for mission templates

Mission template code clean up

---

styles/blocks/missionbg.css

Mission timeline button fix. CSS only changes applied for Mission templates

timeline button fix (mission template)

---

components/en/redirect-dynamic.embed.html

Isolated to only pages including this component - non-breaking javascript added.

dynamic redirect implementation for old components

---

components/en/three-cards.embed.html
styles/blocks/missionbg.css
styles/blocks/missiontimeline.css

Small css spacing issues (applied only to mission template)

mission template spacing implementation

---

styles/blocks/instructions.css
styles/blocks/missionbg.css
templates/tutorials/tutorials.css
templates/tutorials/tutorials.js

One commit is edits from @ispykenny  for the Mission project
One commit is for my tutorial template for the CCP plan project

Mission + CCP updates

---

templates/tutorials/tutorials.js

If statement now in place to accept local header file on Tutorial template.

Fixing header if statement in Tutorial template

---

styles/legacy/styles.css
templates/default/mission-series/iframe.js
templates/global/nav-default.css
templates/tl/tl.css
templates/tl/tl.js

Edits only apply to Mission iFrame component and TL template environment.

iframe empty button fix and grouped throughline cards

---

templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

tl-v2 implementation

---

components/en/three-cards.embed.html
styles/blocks/checklist.css
styles/blocks/clvideo.css
templates/default/checklist.js

Style edits implemented for PS+Lr video templates

Style edits

---

templates/default/checklist.js
templates/tl/tl.css
templates/tl/tl.js

Small style edits to TL template. 
Launch to Lightroom button fix for checklist PS + LR experiment template

TL template style updates

---

templates/tl/tl.js

fixed video pause issue on safari for TL template

fixed video pause issue on safari for TL template

---

static/twp3/icons/quick.svg
styles/blocks/clvideo.css
templates/default/checklist.js
templates/tl/tl.css
templates/tl/tl.js

- Fixed broken SVG
- Fixed "next step" component for external links

Updates to TL template

---

styles/legacy/styles.css
templates/default/checklist.js

- Fixed index count for checklist card content (checklist component)
- Fixed default footer on mobile (styles)

Checklist and default footer adjustments

---

styles/blocks/missionbg.css

small css fix to remove letter-spacing from mission template h1

removed letter-spacing from mission template header

---

templates/xd/xd.css
templates/xd/xd.js

I'm adjusting the XD template block so that I can style the https://pages.adobe.com/xd/en/design-music-app-with-howard-pinsky
I've copied the default CSS and JS into the respective XD CSS and XD JS template files within the templates folder.
I've modified the headline for the this page via CSS. I've also adjusted the numbering format for the sections.
I've tested against a local version of this page: https://pages.adobe.com/xd/en/test2
I'm not able to get the local version of the https://pages.adobe.com/xd/en/design-music-app-with-howard-pinsky to work but I've made progress.
- [ x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).

Update XD template block

---

styles/blocks/linktexting.css
templates/default/default.js

1 new CSS file for the LinkTexting block.
New additions in default.js for the block. That is probably what requires review.

Changes for Rush Text the Link pages!

---

styles/blocks/nav.css
templates/default/default.js

Allows Product name to link out to its google doc link.
Tested across various projects/pages in staging.

Nav Icon name link fix

---

templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

removed border styles on TL-V2 template step page.

removed h1 border styles in TL-V2 template

---

styles/blocks/instructions.css
styles/legacy/styles.css
templates/default/default.css

-- Footer link colors to mirror a.com footer link colors (improved contrast) 
-- added video duration styles to mission template

Updates to footer link colors and mission template video duration

---

templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

fixed play/pause bug in tl-v2 template for video element

video player fix tl-v2 template

---

templates/wg/wg.css

Allowing authors to conditional render questions with the WG template

added .hidden css styles for conditional rendered questions

---

templates/twp1/twp1.css
templates/twp1/twp1.js

implementation of TwP 1 home page template

New template for TWP 

---

templates/twp1/twp1.css
templates/twp1/twp1.js

kickoff of twp template for single pages.

Implementation of twp template single page

---

templates/twp1/twp1.css
templates/twp1/twp1.js

Round 1 edits for twp template implemented.

twp page style edits

---

templates/smb/smb.js

logo name placement next to icon in nav for smb templates

fixed nav for smb template

---

templates/twp1/twp1.css

implemented nav styling for twp template

twp nav styles

---

templates/twp1/twp1.css

bumped up font size on cta buttons

font weight fix for twp buttons

---

templates/twp1/twp1.css
templates/twp1/twp1.js

Alignment changes to twp template

style updates on twp template

---

templates/twp1/twp1.js

Allowing option sections for step 1 and step 3. TWP template only

twp template edge case for optional sections

---

scripts.js
templates/tl-v2/tl-v2.js

Fixed nav layout for templates including a header block component

fixed header block

---

templates/ai-scientist/ai-scientist.js
templates/twp1/twp1.css

Template style updates. JS code clean up

ai-scientist template updates

---

templates/premiere/premiere.css

CSS style changes to the additional link component using the 'premiere' template.

additional link component in jp/onboarding

---

templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

Added secondary CTA support for templates using TL-V2

added secondary cta support TL-V2

---

templates/tl-v2/tl-v2.js

Check if second CTA is on the page before modifying its attributes.

JS error guard.

---

templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

tl-v2 redesign

---

templates/dynamic/dynamic.js
templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

small css tweaks to tl-v2 template

style adjustments to tl-v2 template

---

templates/tl-v2/tl-v2.css

fixed positioning of hero video thumbnail on step page to be centered.

tl-v2 hero fix

---

templates/tl-v2/tl-v2.css
templates/tl-v2/tl-v2.js

Aligning icons on tl-v2 page and making mini product icons in cards optional
font2 icon included

tl-v2 -> align icons

---

templates/tl-v2/tl-v2.js

making card icons optional on template tl-v2

making card icons optional

---

templates/tl-v2/tl-v2.css

Update to TL-V2 Template to contain correct spectrum blue hex value.

added spectrum blue to hyper link

---

templates/tl-v2/tl-v2.js

removed trim function on icon string

---

static/twp3/icons/fonts2.svg
templates/tl-v2/tl-v2.js

fixed alignment issue where the icon-lists are.

fixed alignment issue on TL-V2

---

styles/blocks/nav.css
templates/default/default.css
templates/default/default.js

Preventing the harsh load in of the nav icon in the blocks environment.

fixing rendering of nav icon

---

styles/blocks/nav.css
templates/default/default.css

Moved styles from nav block header image into the default style css file

Changing location of header img styles

---

styles/blocks/card.css
styles/blocks/hero.css
styles/blocks/video.css
templates/default/default.css
templates/default/default.js

Changes styles for hero, video, card blocks. CSS changes only with added-class support.

Block modifications

---

templates/cc-growth/cc-growth.css
templates/cc-growth/cc-growth.js
templates/cc-growth/icons.js

Included lazy loading in icon library

refactor icon page (cc-growth)

---

styles/legacy/styles.css
templates/speechtotext/speechtotext.css
templates/speechtotext/speechtotext.js

Adding fixes for Pr Speech to Text layout bugs created by changed markup. New styling for select menus, adding down caret to right side.

Pr Speech to Text layout fixes + addition of <select> styling/SVG

---

templates/ai-scientist/ai-scientist.css
templates/ai-scientist/ai-scientist.js

Small CSS tweaks for ai-scientist template. Specifically for KO ai-scientist template pages.

style changes for ai-scientist template

---

static/global/select-caret.svg

What the title says. Adding SVG for <select> menu down caret

Forgot my git add to add the SVG -_-;

---

templates/learn/learn.css
templates/learn/learn.js

These CSS and markup changes only apply to https://pages.adobe.com/lightroom-classic/en/learn/color-grading/ and child pages. No other pages are impacted.

Fixins to Lightroom Classic Color Grading layout issues

---

scripts.js
templates/dynamic/dynamic.js
templates/tl-masterclass/tl-masterclass.js

WIP implementation of dynamic sheet environment

Working on dynamic sheet data

---

templates/lr-ps/lr-ps.js

Fixing bad icon path in lr-ps JS file

---

templates/stock-advocates/stock-advocates.css

Changes to styles for Advocates

Advocates style updates

---

styles/blocks/form.css
templates/default/default.js

Ensuring nav icons display correct app icon.  (block)
Fixed spacing issue on form block.

Block refresh

---

templates/status/status.css
templates/status/status.js

status page initial upload

---

templates/status/status.js

Updates to loading state for status page
https://pages.adobe.com/creativecloud/en/status-page/

update loading state for status page

---

templates/status/status.js

only display pages that have a 404 status

status page 404 checker fix

---

styles/blocks/nav.css

updated blog app name color in nav

---

templates/stock-advocates/stock-advocates.css
templates/stock-advocates/stock-advocates.js

Stock Advocates updates, add video block

---

templates/stock-advocates/stock-advocates.css

Stock Advocates / artist bio styles

Stock Advocates / artist bio styles

---

styles/blocks/instructions.css
styles/blocks/sampleprojects.css
styles/blocks/videocontent.css
templates/default/content-asset.js
templates/default/default.js
templates/lr-ps/lr-ps.js

Resolve some image rendering from sheet. Allowing external/internal image src options.

Fixing local/external image src options or LR-PS template

---

styles/blocks/scrollto.css
styles/blocks/scrolltop.css
styles/blocks/videocontent.css
templates/default/calloutcardstitle.js
templates/default/content-asset.js
templates/default/default.js
templates/default/scrollTop.js
templates/default/scrollto.js
yarn.lock

New blocks implemented 
1. videocontent
2. hr
3. sectiontitle
4. downloadcallouts
5. scrollto
6. scrolltop
7. cardcallouttitle
8. cardcallouts

New blocks implemented 

---

.tools/run-sync.js
README.md
package.json

- add scripts details, samples
- update inner CDN link
ref: https://github.com/adobe/pages/issues/361

hlx3 migration: update readme

---

.tools/run-compare.js
.tools/run-sync.js
.tools/util.js

Parameterize comparison tool

---

styles/blocks/card.css
styles/blocks/cardcallouts.css
styles/blocks/cardcallouttitle.css

style bump for card and cardcallouts blocks

block [card, cardcallouts] styles bump

---

components/en/lr-ps-show-more/lr-ps-show-more.js
pages/scripts/scripts.js
templates/lr-ps/lr-ps.css
templates/lr-ps/lr-ps.js
templates/lr-ps/tl.css
templates/tl/tl.js

- switch `hlx_` prefixes to to `media_`

Migration hot fixes

---

pages/blocks/form/form.css
pages/blocks/form/form.js
pages/blocks/form/slide-form.js
templates/smb/smb.css

JS and style fixes for Forms (slide form)

Form fix hlx3

---

pages/blocks/card/card.css
pages/blocks/cardcallouts/cardcallouts.css
pages/blocks/cardcallouttitle/cardcallouttitle.css
pages/blocks/downloadcardstitle/downloadcardstitle.css
pages/scripts/scripts.js
scripts.js

Added fixes for blocks used in "which app" page.
/creativecloud/en/which-app/
also removed the setWidth function from scripts.js that serves no purpose throughout pages.adobe

Which app fixes

---

pages/scripts/scripts.js
scripts.js

instruments funnel for:
`top`, `load`, `click`
https://microfunnel--pages--adobe.hlx3.page/creativecloud/en/ete/how-adobe-apps-work-together/?rum=on

initial microfunnel instrumentation

---

templates/lr-ps/lr-ps.js

Fixed condition spelling error

fixed broken js on lr-ps template

---

pages/scripts/scripts.js
scripts.js
scripts/twp.js
scripts/twpds.js
templates/dynamic/dynamic.js
templates/learn/learn.js

fix: only add valid urls to publish dependencies

---

tools/sidekick/config.js

Like #379, but also for unpublish.

feat(sidekick): purge prod url also on unpublish

---

pages/blocks/content/content.css
pages/blocks/form/form.css
pages/scripts/scripts.js

new content block && added some helper class to the form block.

New content block

---

pages/blocks/form/form.css
pages/blocks/form/slide-form.js
styles/legacy/styles.css
templates/dynamic/styles.css

Update slide block styles and enabled helper classes for this block.

Form block update

---

pages/blocks/fullwidthimage/fullwidthimage.css
pages/blocks/herowithimage/herowithimage.css
pages/scripts/scripts.js
pages/styles/default.css

New css for said blocks and added to `blocksWithOptions`  array for these new blocks.

Added a few new blocks for MAX page

---

templates/mobile-awareness/decorators/decorateAppPage.js
templates/mobile-awareness/decorators/decorateGeneral.js
templates/mobile-awareness/decorators/decorateLanding.js
templates/mobile-awareness/decorators/decorateNav.js
templates/mobile-awareness/mobile-awareness.css
templates/mobile-awareness/mobile-awareness.js
templates/mobile-awareness/scripts/branch.js
templates/mobile-awareness/scripts/scripts.js
templates/mobile-awareness/styles/appPage.css
templates/mobile-awareness/styles/landing.css
templates/mobile-awareness/styles/nav.css

The mobile-awareness template is specifically for the Growth team's project to increase user awareness of the mobile apps that they are entitled to under the CPP or PS single app plans.
Landing:
https://main--pages--midblue.hlx3.page/creativecloud/en/mobile-apps-in-your-plan/
https://main--pages--midblue.hlx3.page/creativecloud/en/mobile-apps-in-your-plan/cpp
App-specific:
https://main--pages--midblue.hlx3.page/creativecloud/en/mobile-apps-in-your-plan/lightroom-for-mobile
https://main--pages--midblue.hlx3.page/creativecloud/en/mobile-apps-in-your-plan/fresco
https://main--pages--midblue.hlx3.page/creativecloud/en/mobile-apps-in-your-plan/photoshop-on-ipad
https://main--pages--midblue.hlx3.page/creativecloud/en/mobile-apps-in-your-plan/photoshop-express
I added css and js for a new …

Add template for Mobile Awareness (creativecloud/en/mobile-apps-in-your-plan/)

---

templates/consonant/blocks/header/header.css
templates/consonant/consonant.js

Fix anchor links from opening in new tab, and fix a typo in the css styling

fix(consonant-blocks): fix anchor links from opening in new tab

---

templates/consonant/blocks/header/header.js
templates/consonant/consonant.js

1st Bug fix: typo in checking for anchor link, should be index 0 not -1
2nd Bug fix: prevent `can't read textContent of null` error

fix(consonant-blocks): 2 bug fixes in the header - javascript

---

pages/blocks/textoverbackground/textoverbackground.css
pages/blocks/textoverbackground/textoverbackground.js
pages/scripts/scripts.js

Based on the request here https://github.com/adobe/pages/issues/415
Used in this example:
url - https://text-over-background--pages--adobe.hlx.live/cc-growth-sandbox/test/text-over-background

Initial implementation of text over background block

---

pages/blocks/textoverbackground/textoverbackground.css

Small CSS change.
URL example: 
https://text-over-background--pages--adobe.hlx3.page/cc-growth-sandbox/test/text-over-background

Forcing all <h1-h6> to be #ffffff on dark backgrounds

---

pages/blocks/button-group/button-group.css
pages/scripts/scripts.js

New block to allow side-by-side buttons. 
Added style changes for ccexpress class
used here
https://button-groups-block--pages--adobe.hlx3.page/express/en/learn/thank-you

Button groups block

---

templates/stock-advocates/stock-advocates.css
templates/stock-advocates/stock-advocates.js

**Added features:**
- Auto-play on the HomePage carousel added
- Auto-play stops if you manually change carousel slides to prevent annoyance 
**Accessibility Fixes: (for advocates pages only)**
- Header nav keyboard accessibility
- Headings structure hierarchy
**General FIxes:**
- Fix inconsistency in CSS indentation in `stock-advocates.css`
- Fix inconsistency in Fonts and Buttons (for advocates pages only)
- Fix small bugs of text overlaying each other (ie: pre-footer text and header menu overlaying the logo on smaller screens)
- Style fixes, now looks more like the [XD Mockup](https://xd.adobe.com/view/91588aa8-71a6-4081-9324-c0e1eb9a0c16-c40b/)
index:
https://advocates--pages--webistry-development.hlx3.page/stock/en/advocates/drafts/
creative briefs: …

feat(advocates-refresh): a fresh new look on advocates pages

---

templates/stock-advocates/stock-advocates.css
templates/stock-advocates/stock-advocates.js

Homepage with video:
https://advocates_videos--pages--webistry-development.hlx3.page/stock/en/advocates/drafts/
Artist pages with videos:
https://advocates_videos--pages--webistry-development.hlx3.page/stock/en/advocates/drafts/artists/anna-neubauer
https://advocates_videos--pages--webistry-development.hlx3.page/stock/en/advocates/drafts/artists/chris-robinson
https://advocates_videos--pages--webistry-development.hlx3.page/stock/en/advocates/drafts/artists/cole-ndelu
https://advocates_videos--pages--webistry-development.hlx3.page/stock/en/advocates/drafts/artists/mizuho-call
The homepage video should autoplay and be full-width.

Advocates video block & columns font-weight fix

---

pages/blocks/herocontent/herocontent.css
pages/blocks/herocontent/herocontent.js
pages/blocks/productcta/productcta.css
pages/blocks/productcta/productcta.js
pages/blocks/twocolumn/twocolumn.css
pages/blocks/twocolumn/twocolumn.js
pages/blocks/youtube/youtube.css
pages/blocks/youtube/youtube.js
pages/scripts/scripts.js

example:
https://two-column--pages--adobe.hlx3.page//cc-growth-sandbox/test/cass-file-hero

Two column

---

pages/blocks/herocontent/herocontent.css
pages/blocks/productcta/productcta.css
pages/blocks/youtube/youtube.css
pages/scripts/scripts.js

example:
https://two-column--pages--adobe.hlx3.page//cc-growth-sandbox/test/cass-file-hero

Youtube block

---

pages/blocks/herocontent/herocontent.css
pages/blocks/productcta/productcta.css
pages/scripts/scripts.js

example
https://two-column--pages--adobe.hlx3.page//cc-growth-sandbox/test/cass-file-hero

Prouctcta block

---

templates/consonant/blocks/share/share.css
templates/consonant/consonant.js

- Fix the title's share feature in the article pages.
Test url: https://fix-share-in-article--pages--webistry-development.hlx3.page/stock/en/artisthub/articles/spring-call-for-content-reflect-and-refresh
[before](https://main--pages--adobe.hlx3.page/stock/en/artisthub/articles/spring-call-for-content-reflect-and-refresh) / [after](https://fix-share-in-article--pages--webistry-development.hlx3.page/stock/en/artisthub/articles/spring-call-for-content-reflect-and-refresh)

fix(share-article): fix share feature in title article

---

pages/blocks/learnmoresmart/learnmoresmart.css
pages/blocks/learnmoresmart/learnmoresmart.js

Example:
https://learnmore-smart-block--pages--adobe.hlx3.page/cc-growth-sandbox/test/cass-file-hero

learn-more-smart-block

---

pages/blocks/faq/faq.css
pages/blocks/faq/faq.js

example shown here
https://faq-block--pages--adobe.hlx3.page/premiere-rush/en/free-assets/faq

implement accordion for faq-block

---

pages/blocks/herocontent/herocontent.css

removes all margin from headers.
used here
https://headercontent-block-dev--pages--adobe.hlx3.page/premiere-rush/en/free-assets/step-one

support: added noheadermargin class

---

pages/blocks/learnmoresmart/learnmoresmart.css
pages/blocks/learnmoresmart/learnmoresmart.js
pages/scripts/scripts.js

Picking pathname off destination url to avoid issues in different environments (localhost/preview/production)
example: https://learnmore-smart-block--pages--adobe.hlx3.page/premiere-rush/en/free-assets/step-two

Fix spacing on learnmoresmartblock

---

pages/blocks/learnmoresmart/learnmoresmart.css
pages/blocks/learnmoresmart/learnmoresmart.js

Example shown at the bottom here
https://learnmore-smart-block--pages--adobe.hlx3.page/premiere/en/free-assets/step-one

fix: learnmoresmart-block is now clickable

---

templates/consonant/blocks/columns/columns.css
templates/consonant/blocks/video/video.css
templates/consonant/blocks/video/video.js
templates/consonant/consonant.css

- Fix `span.detail` not being centered when outside of a block
- Fix grouped button spacing ([before ](https://main--pages--adobe.hlx3.page/stock/en/artisthub/drafts/block-test)/ [after](https://video-mp4--pages--webistry-development.hlx3.page/stock/en/artisthub/drafts/block-test))
- Tweak video block
- Add (No-controls) variant for hiding video controls
- Allow .mp4 links for video block
Test URL: https://video-mp4--pages--webistry-development.hlx3.page/stock/en/artisthub/drafts/block-test

feat(video): allow .mp4 links for video block

---

components/en/back-next-steps/back-next-steps.js
components/en/tutorial-context/tutorial-context.js
components/internal/tutorial-context-langs.js
pages/blocks/tutorial-guide/tutorial-guide.js
templates/learn/learn.css
templates/tutorials/navLayout.js
templates/tutorials/tutorials.css
templates/tutorials/tutorials.js

Example shown here
https://tutorial-guide--pages--adobe.hlx3.page/creativecloud/es/photography-plan/lightroom-classic/color-grading/dive-deep/step?10

Tutorial guide

---

templates/tutorials/tutorials.js

Nav style fix for tutorial template.
example:
https://tutorial-guide--pages--adobe.hlx3.page/creativecloud/pt/photography-plan/ps-lrc/

nav style fix:

---

templates/consonant/blocks/header/header.css
templates/consonant/blocks/header/header.js
templates/consonant/blocks/video/video.js
templates/consonant/consonant.css
templates/consonant/consonant.js
templates/stock-advocates/stock-advocates.js

- Fix lazy-load for videos as suggested here: https://github.com/adobe/pages/pull/439
- Fix async loading for header to help with CLS score
https://performance--pages--webistry-development.hlx3.page/stock/en/artisthub/drafts/block-test
https://performance--pages--webistry-development.hlx3.page/stock/en/artisthub/get-inspired/creative-trends/be-bold-visual-trend-powerfully-playful
https://performance--pages--webistry-development.hlx3.page/stock/en/advocates/
https://performance--pages--webistry-development.hlx3.page/stock/en/advocates/artists/mizuho-call

fix(performance): lazy load for videos & better loading for header

---

templates/stock-advocates/stock-advocates.css
templates/stock-advocates/stock-advocates.js

Style changes requested by Anna & Rod from the Stock Advocates team. Especially mobile-responsiveness fixes.
Test urls: 
- Home: [Before ](https://pages.adobe.com/stock/en/advocates/)/ [After](https://advocates--pages--webistry-development.hlx3.page/stock/en/advocates/) 
- Artist Development Fund: [Before ](https://pages.adobe.com/stock/en/advocates/artist-development-fund)/ [After](https://advocates--pages--webistry-development.hlx3.page/stock/en/advocates/artist-development-fund)
- A Creative Brief Page: [Before ](https://pages.adobe.com/stock/en/advocates/joyful-rhythm)/ [After](https://advocates--pages--webistry-development.hlx3.page/stock/en/advocates/joyful-rhythm)
- An Artist Page: [Before ](https://pages.adobe.com/stock/en/advocates/artists/jerilyn-guerrero)/ …

fix(stock-advocates): style changes made as requested by anna & rod

---

templates/consonant/blocks/header/header.css
templates/stock-advocates/stock-advocates.css

- Small style fixes
- Major bug fix: header dropdown overlaying itself if it takes the whole screen height
Before / After:
Test URL: https://stock--pages--webistry-development.hlx3.page/stock/en/artisthub/

fix(bug-fixes): style fixes and header dropdown bug fix

---

package-lock.json
templates/consonant/blocks/breadcrumbs/breadcrumbs.css
templates/consonant/blocks/footer/footer.css
templates/consonant/blocks/images/images.css
templates/consonant/blocks/marquee/marquee.css
templates/consonant/blocks/marquee/marquee.js
templates/consonant/blocks/separator/separator.css
templates/consonant/blocks/video/video.css
templates/consonant/consonant.css
templates/consonant/consonant.js

- Small bug fixes in the footer (The position of copyright text was off, and the hover on the main logo looked bad.)
- Fix issue with hiding the invisible block (Section-metadata) accidentally hid the whole section instead.
- Changes in font sizing and width/heights of sections according to the consonant 5.0 designs
- Fix captions in marquee
- Add caption to small image in marquee
- New marquee block re-made to fit the specs: https://xd.adobe.com/view/095884b9-8a10-405c-8820-19d692f2a334-5c0b/screen/de7d0323-f8b5-4f7f-9269-631da47abf7f/
Test URLs: 
https://consonant-5-0--pages--webistry-development.hlx.page/stock/en/artisthub/drafts/consonant-5-0
https://consonant-5-0--pages--webistry-development.hlx.page/stock/en/artisthub/drafts/block-library

Consonant 5.0 Marquee

---

helix-sitemap.yaml
sitemap-index.xml

Setting up a general all purpose sitemap for pages.adobe.com. 
Testing: Unable to fully test until on main. helix-sitemap sheet is setup, AWS is configured for the index and index is functioning. These changes are modeled from b.a.com approach to sitemap.

Sitemap setup

---

templates/tutorials/tutorials.css

See the bottom of the page (the cards block)
Original:
https://main--pages--adobe.hlx3.page/creativecloud/es/photography-plan/lightroom-classic/hsl-target-adjustment
Fixed:
https://tutorials-cards--pages--adobe.hlx.page/creativecloud/es/photography-plan/lightroom-classic/hsl-target-adjustment

tutorials cards styles.

---

pages/blocks/quickactions/jsonSetUp.js
pages/blocks/quickactions/quickactions.css
pages/blocks/quickactions/quickactions.js
pages/blocks/quickactions/sideBar.css

Addendum to this PR: https://github.com/adobe/pages/pull/451
Following up on feedback, this is several extremely minor changes to the quick-actions block.
The project in question that uses this launches today.

Minor style changes for quick-actions block

---

templates/premiere/premiere.css

Resolving issue: [MWPW-111022](https://jira.corp.adobe.com/browse/MWPW-111022)
Current: https://main--pages--adobe.hlx.page/premiere/en/yts-livestream
Testing: https://premiere-css-fix--pages--adobe.hlx.page/premiere/en/yts-livestream

Fixing unaligned card height.

---

templates/tl-masterclass/tl-masterclass.js

- Fix the opacity issue.
Test:
https://main--pages--adobe.hlx.page/premiere/en/14-day-trial/step?1
Fix:
https://tl-masterclass-fix--pages--adobe.hlx.page/premiere/en/14-day-trial/step?1

Fix the opacity issue.

---

templates/tl-v2/tl-v2.js

Requested by Cass Waldman via Slack.
Before: https://main--pages--adobe.hlx.page/creativecloud/en/ai-and-ps-together/
After: https://tl-v2-fix--pages--adobe.hlx.page/creativecloud/en/ai-and-ps-together/

Enable appearMain()

---

templates/stock-advocates/stock-advocates.css

fix(advocates): fix css object-fit cover

---

scripts/scripts.js

Use the correct configuration id for Privacy
https://privacy-fix--pages--adobe.hlx3.page/

fix: use production config for Privacy

---

pages/blocks/nav/nav.js
pages/blocks/quickactions/createSideBar.js
pages/blocks/quickactions/jsonSetUp.js
pages/blocks/quickactions/quickactions.css
pages/blocks/quickactions/quickactions.js

v6 to v7 migration for the quickaction page template
v6: https://main--pages-v6--kptdobe.hlx.page/photoshop/en/quick-actions/
v7 broken: https://main--pages--adobe.hlx.page/photoshop/en/quick-actions/
v7 fixed: https://fix-v7-quickactions--pages--adobe.hlx.page/photoshop/en/quick-actions/

fix: quickactions template

---

components/en/form/form.css
pages/blocks/form/form.css
pages/blocks/form/form.js
styles/legacy/styles.css
templates/ai-scientist/styles.css
templates/cc-growth/styles.css
templates/checklist/styles.css
templates/creativecloud/styles.css
templates/default/default.js
templates/dynamic/styles.css
templates/ete/styles.css
templates/ihearttech/styles.css
templates/indesign/styles.css
templates/learn/styles.css
templates/lr-ps/styles.css
templates/on24/styles.css
templates/photoshop/styles.css
templates/premiere/styles.css
templates/smb/styles.css
templates/speechtotext/styles.css
templates/status/styles.css
templates/stock-advocates/stock-advocates.js
templates/tl-masterclass/styles.css
templates/tl-v2/styles.css
templates/tl/styles.css
templates/tutorials/styles.css
templates/twp1/styles.css
templates/video-series/default.css
templates/wg/default.css

Issue ticket: [MWPW-123053](https://jira.corp.adobe.com/browse/MWPW-123053)
Before: https://main--pages--adobe.hlx.page/general/en/blog-survey22/
After: https://accessibility-issue--pages--adobe.hlx.page/general/en/blog-survey22/

Accessibility issue for form
